// Generated by CoffeeScript 1.4.0
(function() {
  var Client, Collector, EventEmitter, Worker, client, collector, config, librato, middleware, worker, _ref;

  EventEmitter = require('events').EventEmitter;

  Client = require('./client');

  Worker = require('./worker');

  Collector = require('./collector');

  middleware = require('./middleware');

  _ref = {}, collector = _ref.collector, client = _ref.client, worker = _ref.worker, config = _ref.config;

  librato = new EventEmitter();

  librato.configure = function(newConfig) {
    config = newConfig;
    collector = new Collector();
    client = new Client(config);
    return worker = new Worker({
      job: librato.flush
    });
  };

  librato.increment = function(name) {
    var _ref1;
    return collector.increment("" + ((_ref1 = config.prefix) != null ? _ref1 : '') + name);
  };

  librato.timing = function(name, valueMs) {
    var _ref1;
    return collector.timing("" + ((_ref1 = config.prefix) != null ? _ref1 : '') + name, valueMs);
  };

  librato.measure = librato.timing;

  librato.start = function() {
    return worker.start();
  };

  librato.stop = function() {
    worker.stop();
    return librato.flush();
  };

  librato.flush = function() {
    var data, queue;
    queue = [];
    collector.flushTo(queue);
    if (queue.length) {
      data = {
        gauges: queue,
        source: config.source
      };
      return client.send(data, function(err) {
        if (err != null) {
          return librato.emit('error', err);
        }
      });
    }
  };

  librato.middleware = middleware(librato);

  module.exports = librato;

}).call(this);
